
fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class:     Application\Sonata\UserBundle\Entity\User
    #user_class:     AppBundle\Entity\User
    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group
        #group_class:   AppBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager # If you're using doctrine orm (use sonata.user.mongodb.group_manager for mongodb)
    service:
        user_manager: sonata.user.orm.user_manager   # If you're using doctrine orm (use sonata.user.mongodb.user_manager for mongodb)
    profile:
        form:
            validation_groups:  [Default]
    change_password:
        form:
            validation_groups: [myChangePassword]
    registration:
        form:
            validation_groups:  [Default]
    from_email:
        address:        claravista@actions-pdv-l.fr
        sender_name:    Lancel - Clienteling
